directories:
  project_dir: "terainet"
  scripts_dir: "scripts"
  samples_dir: "samples"
  images_dir: "images"

scripts:
  get_image_urls_script: "get_image_urls_from_lila_bc.sh"
  download_images_script: "download_images_from_lila_bc.sh"
  unzip_and_copy_script: "unzip_and_copy_lila_bc_images.sh"
  prep_amur_tiger_images: "prep_amur_tiger_images.sh"
  run_megadetector: "run_megadetector.py"
  copy_snipped_images: "copy_snipped_images.sh"

kaggle:
  images_input_dir: "kaggle/input/images/images"
  images_output_dir: "kaggle/working/images"

megadetector:
  megadetector_dir: "megadetector"
  megadetector_file: "md_v5a.0.0.pt"
  megadetector_out_file: "md_out.json"

mewc:
  snip_dir: "snips"
  lower_conf: 0.05
  snip_size: 600

classes:
  num_classes: 10
  tiger: 1
  leopard: 2
  black_bear: 3
  other_carnivores: 4
  deer: 5
  wild_boar: 6
  buffalo: 7
  rhino: 8
  elephant: 9
  bird: 10

train_params:
  train_ratio: 0.8
